### ISSUE TITLE
gulp dev (sometimes) doesn't build chrome directory?

### ISSUE THREAD

**Issue by groovecoder** [codesy/widgets#102]
Steps to reproduce:
1. Run `gulp dev`
2. Load unpacked extension from the `chrome/` directory

Expected results:
Extension should always have latest file-changes

Actual results:
Sometimes the extension loads an older version? Like the gulp task isn't actually updating the files in `chrome/`?

**Comment by jdungan** [comment]
Check out #103.  This cleans up the confusing settings for building packages.

**Comment by jdungan** [comment]
OBE.  Gulp dev is long gone.
