### ISSUE TITLE
Create post-install "first run" experience

### ISSUE THREAD

**Issue by groovecoder** [codesy/widgets#25]
After installing the Chrome extension, the first run should (re-) open the codesy home page so the user can sign in with GitHub.

**Comment by jdungan** [comment]
Should this be closed?

**Comment by groovecoder** [comment]
I think not. After the install, we should automatically open a tab to api.codesy.io.

**Comment by jdungan** [comment]
Does c6c03662b3b355e6c47606caabac8baad9af2fe7 fix this?

**Comment by groovecoder** [comment]
I'll try this again when I can get the gulp tasks to run

**Comment by codesy-testuser** [comment]
Looks good to me.
