### ISSUE TITLE
Test installation from Chrome Web Store

### ISSUE THREAD

**Issue by groovecoder** [codesy/widgets#5]
I submitted the extension to the Chrome Web Store, though it's only available to us users who sign into the store with @codesy.io accounts.

https://chrome.google.com/webstore/detail/hopifhdlfjonfmboekeejdilgkkockjb/publish-accepted?authuser=1

But when I deactivate my source code extension and activate the extension from CWS it doesn't work. :(

**Comment by groovecoder** [comment]
@jdungan:
<img width="1440" alt="crx-web-store-error" src="https://cloud.githubusercontent.com/assets/71928/13197679/7c13ad26-d7ba-11e5-9a2b-d9284f0914fa.png">

**Comment by jdungan** [comment]
Installation works from Chrome, AMO, an Opera stores.

![screen shot 2016-07-06 at 2 28 35 pm](https://cloud.githubusercontent.com/assets/1707538/16631810/ad4ea5f2-4386-11e6-92f8-32e44d93dda9.png)
