### ISSUE TITLE
dev-start keeps appending entries to manifest.json?

### ISSUE THREAD

**Issue by groovecoder** [codesy/widgets#65]
Steps to reproduce:
1. Run dev-start
2. Change branches a few times

Expected results:
In manifest.json, `permissions` and `matches` should only contain 1 entry each for the 127.* domains

Actual results:
`permissions` and `matches` have:
```
    "https://127.0.0.1:8443/",
    "https://127.0.0.1:8443/",
    "https://127.0.0.1:8443/"
```
and
```
      "*://127.0.0.1:*/*",
      "*://127.0.0.1:*/*",
      "*://127.0.0.1:*/*"
```

**Comment by jdungan** [comment]
I can't reproduce.  Check your prod/manifest.json.

**Comment by groovecoder** [comment]
This was only happening on my machine. Clearing `manifest.json` fixed it up.

**Comment by jdungan** [comment]
The gulp task for manifest.json and package.json are holding the new appended values.

**Comment by jdungan** [comment]
This was caused by using =require("manifest.json") to read the manifest file.   Using JSON.parse(fs.readFileSync("manifest.json")) instead to open the file on each play of the task.
