### ISSUE TITLE
Can the widget use an iframe instead of a div container 

### ISSUE THREAD

**Issue by groovecoder** [codesy/widgets#70]
@jsatt had a great idea when I explained the duplicate `styles.css` issue to him.

Make the codesy widget simply draw an iframe to the bid widget url. I.e., just do like Spotify's architecture. ;)

**Comment by groovecoder** [comment]
@jdungan and I discussed this **is** probably our long-term strategy. But we don't need to pick it up right now.

**Comment by groovecoder** [comment]
We might **have** to do this? Looks like GitHub implemented a Content Security Policy that blocks injected style sources.

![chrome-github-csp](https://cloud.githubusercontent.com/assets/71928/11603169/7586aad2-9aa5-11e5-8682-1ceca4380ab7.png)

**Comment by jdungan** [comment]
Found this strategy: https://work.planbox.com/blog/development/coding/bypassing-githubs-content-security-policy-chrome-extension.html

Seems a bit sneeky but I'll give it a try.  also, not sure how FF will react (a bridge for another day).

**Comment by jdungan** [comment]
Added codesy domain to the csp for script-src, style-src, and frame-src but received: 
```
Refused to display 'https://127.0.0.1:8443/bid/?url=https%3A%2F%2Fgithub.com%2Fcodesy%2Fwidgets%2Fissues%2F70%23issuecomment-162101575' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.
```

To get the iframe to load, I commented out the following line in MIDDLEWARE_CLASSES:
```
django.middleware.clickjacking.XFrameOptionsMiddleware
```

**Comment by groovecoder** [comment]
Oh the irony.

We're over-writing GitHub's CSP so we can put a codesy.io `iframe` on GitHub pages.

At the same time, we **don't** want to let any site on the web iframe *our* pages, or now **we** are opening ourselves to [Clickjacking attacks](https://www.owasp.org/index.php/Clickjacking). The best fix is to remove XFrameOptionsMiddleware, **AND** add our **own** CSP with `frame-ancestors github.com;` directive.

**Comment by groovecoder** [comment]
I filed https://github.com/codesy/codesy/issues/185 to make the corresponding server-side change to add the `frame-ancestors` CSP directive.

**Comment by jdungan** [comment]
It wasn't easy to find so, for the record, here's how to load the webRequest API for firefox addon's:

    {Cc, Ci, Cu} = require("chrome");
    {WebRequest} = Cu.import("resource://gre/modules/WebRequest.jsm", {});

**Comment by jdungan** [comment]
Here's a potential problem from the WebExtensions wiki:

"At this time, it is not possible to publish WebExtensions to addons.mozilla.org."

Hopefully this will change by the time we are finished.  If not, we are supposed to be able to host our on (signed) addon.  Which may be better than pointing users to the store.

**Comment by groovecoder** [comment]
Implemented for Chrome in https://github.com/codesy/widgets/pull/80
