### ISSUE TITLE
Widget gets logged-out when user visits a page other than home page

### ISSUE THREAD

**Issue by groovecoder** [codesy/widgets#71]
Steps to reproduce:
1. Sign in to codesy at the codesy home page
2. Use the widget - make a bid, make a claim, etc.
3. Go to a codesy page that isn't the home page - e.g., an admin page, or the claim detail page
4. Go back to an issue on GitHub

Expected results:
The codesy widget should be signed-in

Actual results:
The codesy widget is signed-out, and I have to refresh the codesy home page to make it sign back in

**Comment by jdungan** [comment]
Firefox or Chrome?

**Comment by groovecoder** [comment]
Both.

**Comment by jdungan** [comment]
Oh.  New pages are resetting the token key.  Solutions:

ugly: put the token element on every page
not ugly: smarten up the home content script to not reset the token on non-home pages

**Comment by groovecoder** [comment]
Also, I just made Firefox and Chrome labels. But let's assume anything without one of those labels happens in both?

**Comment by jdungan** [comment]
This fixed the problem with other codesy pages, but broken clearing the token when signing out.
