### ISSUE TITLE
iframe widget doesn't work in Firefox

### ISSUE THREAD

**Issue by groovecoder** [codesy/widgets#82]
@jdungan can provide details, but there's a bug in Firefox that won't allow the Add-on to over-write the csp header value.

**Comment by jdungan** [comment]
The bug is  Bug 1232849

**Comment by groovecoder** [comment]
Note: https://bugzilla.mozilla.org/show_bug.cgi?id=1232849 landed in mozilla-central. Should be able to check it in Firefox Nightly and/or Firefox Developer Edition.

**Comment by groovecoder** [comment]
It does now!
